import type { Site, Artifact } from '@/types';

const allArtifacts: Artifact[] = [
  {
    id: 'art-1',
    siteId: 'site-1',
    title: {
      en: 'Mughal Miniature Painting',
      hi: 'मुगल लघु चित्रकला',
      kn: 'ಮೊಘಲ್ ಸೂಕ್ಷ್ಮಚಿತ್ರ',
      or: 'ମୋଗଲ କ୍ଷୁଦ୍ର ଚିତ୍ର',
    },
    description: {
      en: 'A detailed miniature painting characteristic of the Mughal era, often depicting courtly scenes, historical events, or portraits. These paintings are known for their intricate details and vibrant colors.',
      hi: 'मुगल काल की विस्तृत लघु चित्रकला, जो अक्सर दरबारी दृश्यों, ऐतिहासिक घटनाओं या प्रतिमाओं को दिखाती है। ये चित्र सूक्ष्म विवरण और जीवंत रंगों के लिए प्रसिद्ध हैं।',
      kn: 'ಮೊಘಲ್ ಯುಗಕ್ಕೆ ಸಂಬಂಧಿಸಿದ ಸೂಕ್ಷ್ಮ ಚಿತ್ರಗಳು; ಸಾಮಾನ್ಯವಾಗಿ ಅರಾಮೆರೆಯ ದೃಶ್ಯಗಳು, ಐತಿಹಾಸಿಕ ಘಟನೆಗಳು ಅಥವಾ ಭಾವಚಿತ್ರಗಳನ್ನು ಚಿತ್ರಿಸುತ್ತವೆ. ಇವು ಸುಕ್ಷ್ಮವಾದ ವಿವರಗಳು ಮತ್ತು ಜೀವಂತ ಬಣ್ಣಗಳಿಗಾಗಿ ಪ್ರಸಿದ್ಧ.',
      or: 'ମୋଗଲ ଯୁଗର ଏକ ବିସ୍ତୃତ କ୍ଷୁଦ୍ର ଚିତ୍ର, ଯେଉଁଥିରେ ପ୍ରାୟତଃ ଦରବାରର ଦୃଶ୍ୟ, ଐତିହାସିକ ଘଟଣା, କିମ୍ବା ପୋର୍ଟ୍ରେଟ୍ ଚିତ୍ରିତ ହୋଇଥାଏ। ଏହି ଚିତ୍ରଗୁଡ଼ିକ ସେମାନଙ୍କର ଜଟିଳ ବିବରଣୀ ଏବଂ ଜୀବନ୍ତ ରଙ୍ଗ ପାଇଁ ଜଣାଶୁଣା।',
    },
    imageUrlId: 'mughal-painting-artifact',
    modelFileUrl: '/models/mughal_painting.glb',
    fallbackImageUrlId: 'mughal-painting-artifact',
  },
  {
    id: 'art-2',
    siteId: 'site-2',
    title: {
      en: 'Vijayanagara Coin',
      hi: 'विजयनगर सिक्का',
      kn: 'ವಿಜಯನಗರ ನಾಣ್ಯ',
      or: 'ବିଜୟନଗର ମୁଦ୍ରା',
    },
    description: {
      en: 'A gold coin from the Vijayanagara Empire, often featuring deities, royal emblems, or animals. These coins are a testament to the wealth and artistry of the period.',
      hi: 'विजयनगर साम्राज्य का एक सोने का सिक्का, जिसमें अक्सर देवता, राजकीय प्रतीक या पशु अंकित होते हैं। ये उस युग की संपदा और कलात्मकता को दर्शाते हैं।',
      kn: 'ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯದ ಚಿನ್ನದ ನಾಣ್ಯ; ಇದರಲ್ಲಿ ಸಾಮಾನ್ಯವಾಗಿ ದೇವತೆಗಳು, ರಾಜ ಲಾಂಛನಗಳು ಅಥವಾ ಪ್ರಾಣಿಗಳ ಚಿತ್ರಗಳು ಕಾಣುತ್ತವೆ. ಈ ನಾಣ್ಯಗಳು ಆ ಕಾಲದ ಸಂಪತ್ತು ಮತ್ತು ಕಲೆಾಹುಮನೆಯನ್ನು ಪ್ರತಿಬಿಂಬಿಸುತ್ತವೆ.',
      or: 'ବିଜୟନଗର ସାମ୍ରାଜ୍ୟର ଏକ ସୁନା ମୁଦ୍ରା, ଯେଉଁଥିରେ ପ୍ରାୟତଃ ଦେବତା, ରାଜକୀୟ ପ୍ରତୀକ, କିମ୍ବା ପଶୁମାନଙ୍କର ଚିତ୍ର ଥାଏ। ଏହି ମୁଦ୍ରାଗୁଡ଼ିକ ସେହି ସମୟର ସମ୍ପଦ ଏବଂ କଳାର ପ୍ରମାଣ।',
    },
    imageUrlId: 'vijayanagara-coin-artifact',
    modelFileUrl: '/models/vijayanagara_coin.glb',
    fallbackImageUrlId: 'vijayanagara-coin-artifact',
  },
  {
    id: 'art-3',
    siteId: 'site-3',
    title: {
      en: 'Iron Pillar Inscription',
      hi: 'लौह स्तंभ शिलालेख',
      kn: 'ಕಬ್ಬಿಣದ ಸ್ತಂಭದ ಶಿಲಾಶಾಸನ',
      or: 'ଲୌହ ସ୍ତମ୍ଭ ଅଭିଲେଖ',
    },
    description: {
      en: 'A close-up view of the Sanskrit inscriptions on the Iron Pillar of Delhi, located in the Qutub complex. The inscription is a marvel of ancient metallurgy, having resisted rust for over 1600 years.',
      hi: 'कुतुब परिसर के दिल्ली लौह स्तंभ पर संस्कृत शिलालेख का निकटदृष्टि। यह शिलालेख प्राचीन धातुशिल्प का चमत्कार है, जिसने 1600 से अधिक वर्षों तक जंग का प्रतिरोध किया है।',
      kn: 'ದೆಹಲಿಯ ಕುತುಬ್ ಸಂಕೇತದಲ್ಲಿರುವ ಕಬ್ಬಿಣದ ಸ್ತಂಭದ ಸಂಸ್ಕೃತ ಶಿಲಾಶಾಸನದ ಸಮೀಪದ ದೃಶ್ಯ. ಶತಮಾನಗಳಿಂದ ಉಕ್ಕು ಹಾನಿಯನ್ನು ತಡೆಯಿರುವ ಇದು ಪ್ರಾಚೀನ ಲೋಹಶಿಲ್ಪದ ಅದ್ಭುತ ಉದಾಹರಣೆ.',
      or: 'କୁତୁବ କମ୍ପ୍ଲେକ୍ସରେ ଅବସ୍ଥିତ ଦିଲ୍ଲୀର ଲୌହ ସ୍ତମ୍ଭରେ ଥିବା ସଂସ୍କୃତ ଅଭିଲେଖର ଏକ ନିକଟ ଦୃଶ୍ୟ। ଏହି ଅଭିଲେଖ ପ୍ରାଚୀନ ଧାତୁବିଜ୍ଞାନର ଏକ ଚମତ୍କାର, ଯାହା ୧୬୦୦ ବର୍ଷରୁ ଅଧିକ ସମୟ ଧରି କଳଙ୍କିକୁ ପ୍ରତିରୋଧ କରିଆସୁଛି।',
    },
    imageUrlId: 'iron-pillar-artifact',
    modelFileUrl: '/models/iron_pillar_inscription.glb',
    fallbackImageUrlId: 'iron-pillar-artifact',
  },
  {
    id: 'art-4',
    siteId: 'site-2',
    title: {
      en: 'Lakshmi Narasimha Statue',
      hi: 'लक्ष्मी नरसिम्हा प्रतिमा',
      kn: 'ಲಕ್ಷ್ಮಿ ನರಸಿಂಹ ಪ್ರತಿಮೆ',
      or: 'ଲକ୍ଷ୍ମୀ ନରସିଂହ ପ୍ରତିମୂର୍ତ୍ତି',
    },
    description: {
      en: 'A colossal monolithic statue of Lakshmi Narasimha, the fourth incarnation of Lord Vishnu. This masterpiece of Vijayanagara art is located in Hampi.',
      hi: 'भगवान विष्णु के चौथे अवतार लक्ष्मी नरसिंह की एक विशाल एकाशिला मूर्ति। यह विजयनगर कला का उत्कृष्ट उदाहरण है और हम्पी में स्थित है।',
      kn: 'ವಿಷ್ಣುವಿನ ನಾಲ್ಕನೇ ಅವತಾರ ಲಕ್ಷ್ಮಿ ನರಸಿಂಹನ ಏಕಶಿಲಾ ಬೃಹತ್ ಪ್ರತಿಮೆ. ವಿಜಯನಗರ ಕಲೆಯ ಮಿಸ್ಟರ್‌ಪುಳದಾಗಿ ಇದನ್ನು ಹಂಪಿಯಲ್ಲಿ ಕಂಡು ಹಮ್ಮಿಕೊಂಡಿದ್ದಾರೆ.',
      or: 'ଭଗବାନ ବିଷ୍ଣୁଙ୍କ ଚତୁର୍ଥ ଅବତାର ଲକ୍ଷ୍ମୀ ନରସିଂହଙ୍କ ଏକ ବିଶାଳ ଏକଶିଳା ପ୍ରତିମୂର୍ତ୍ତି। ବିଜୟନଗର କଳାର ଏହି ମହାନ କୃତି ହାମ୍ପିରେ ଅବସ୍ଥିତ।',
    },
    imageUrlId: 'lakshmi-narasimha-artifact',
    modelFileUrl: '/models/lakshmi_narasimha.glb',
    fallbackImageUrlId: 'lakshmi-narasimha-artifact',
  },
  {
    id: 'art-5',
    siteId: 'site-2',
    title: {
      en: 'Harihara Statue',
      hi: 'हरिहर प्रतिमा',
      kn: 'ಹರಿಹರ ಪ್ರತಿಮೆ',
      or: 'ହରିହର ପ୍ରତିମୂର୍ତ୍ତି',
    },
    description: {
      en: 'A statue representing Harihara, a fused deity form of Vishnu (Hari) and Shiva (Hara) from Hindu mythology. This represents the synthesis of two major Hindu traditions.',
      hi: 'विष्णु (हरि) और शिव (हर) के सम्मिलित रूप हरिहर का प्रतिनिधित्व करने वाली प्रतिमा। यह हिन्दू परंपराओं के संयोग का संकेत है।',
      kn: 'ವಿಷ್ಣು (ಹರಿ) ಮತ್ತು ಶಿವ (ಹರ) ಅವರ ಒಕ್ಕೂಟವಾದ ದೇವರೂಪ ಹರಿಹರನ ಪ್ರತಿಮೆಯಾಗಿದ್ದು, ಎರಡು ಪ್ರಮುಖ ಹಿಂದೂ ಪರಂಪರೆಯನ್ನು ಸಂಯೋಜನೆಯನ್ನು ಪ್ರತಿಬಿಂಬಿಸುತ್ತದೆ.',
      or: 'ହିନ୍ଦୁ ପୁରାଣରୁ ବିଷ୍ଣୁ (ହରି) ଏବଂ ଶିବ (ହର)ଙ୍କ ମିଳିତ ଦେବତା ରୂପ ହରିହରଙ୍କୁ ପ୍ରତିନିଧିତ୍ୱ କରୁଥିବା ଏକ ପ୍ରତିମୂର୍ତ୍ତି। ଏହା ଦୁଇ ପ୍ରମୁଖ ହିନ୍ଦୁ ପରମ୍ପରାର ସଂଶ୍ଳେଷଣକୁ ପ୍ରତିନିଧିତ୍ୱ କରେ।',
    },
    imageUrlId: 'harihara-artifact',
    modelFileUrl: '/models/harihara_statue.glb',
    fallbackImageUrlId: 'harihara-artifact',
  },
  {
    id: 'art-6',
    siteId: 'site-8',
    title: {
      en: 'Chhau Mask',
      hi: 'छऊ मुखौटा',
      kn: 'ಛೌ ಮುಖೋಟ್ಟು',
      or: 'ଛଉ ମୁଖା',
    },
    description: {
      en: 'A traditional cultural heritage of Purulia, West Bengal, the Chhau mask is used in the Chhau dance, a semi-classical Indian dance with martial, tribal, and folk origins.',
      hi: 'पश्चिम बंगाल के पुरुलिया की पारंपरिक सांस्कृतिक विरासत, छऊ नृत्य में प्रयुक्त मुखौटा। यह आधा-शास्त्रीय नृत्य है जिसमें लोक, आदिवासी और मार्शल तत्व मिलते हैं।',
      kn: 'ಪಶ್ಚಿಮ ಬಂಗಾಳದ ಪುರೂಲಿಯಾಗೆ ಸಂಬಂಧಿಸಿದ ಛೌ ನೃತ್ಯದ ಸಾಂಪ್ರದಾಯಿಕ ಮುಖವಾಡ. ಇದು ಯುದ್ಧಭಾವ, ದೈವೀ ಮತ್ತು ಜನಪದ ಮೂಲಗಳಿಂದ ಬಂದಿರುವ ಅರ್ಧ-ಶಾಸ್ತ್ರೀಯ ನೃತ್ಯದಲ್ಲಿ ಬಳಸಲಾಗುತ್ತದೆ.',
      or: 'ପଶ୍ଚିମବଙ୍ଗର ପୁରୁଲିଆର ଏକ ପାରମ୍ପରିକ ସାଂସ୍କୃତିକ ଐତିହ୍ୟ, ଛଉ ମୁଖା ଛଉ ନୃତ୍ୟରେ ବ୍ୟବହୃତ ହୁଏ, ଯାହାକି ଏକ ଅର୍ଦ୍ଧ-ଶାସ୍ତ୍ରୀୟ ଭାରତୀୟ ନୃତ୍ୟ ଯାହାର ସାମରିକ, ଆଦିବାସୀ, ଏବଂ ଲୋକ ମୂଳ ରହିଛି।',
    },
    imageUrlId: 'chhau-mask-artifact',
    modelFileUrl: '/models/chhau_mask.glb',
    fallbackImageUrlId: 'chhau-mask-artifact',
  },
  {
    id: 'art-7',
    siteId: 'site-4',
    title: {
      en: 'Konark Wheel',
      hi: 'कोणार्क चक्र',
      kn: 'ಕೋನಾರ್ಕ್ ಚಕ್ರ',
      or: 'କୋଣାର୍କ ଚକ',
    },
    description: {
      en: "One of the 24 intricately carved stone wheels of the Konark Sun Temple's chariot structure. These wheels are not just decorative but also function as sundials.",
      hi: "कोणार्क सूर्य मंदिर की रथ संरचना के 24 नक्काशीदार पत्थर के पहियों में से एक। ये पहिये सजावटी होने के साथ-साथ सूर्यघड़ी के रूप में भी कार्य करते हैं।",
      kn: 'ಕೊಣಾರ್ಕ್ ಸೂರ್ಯ ದೇವಾಲಯದ ರಥ ರಚನೆಯಲ್ಲಿ ಕಂಡುಬರುವ 24 ಕಲ್ಲಿನ ಚಕ್ರಗಳೊಂದಾಗಿದೆ. ಇವು ಸೀರಿಯಲ್ ಅಲಂಕಾರಿಕವಲ್ಲದೆ ಸೂರ್ಯಘಂಟೆಯಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ.',
      or: 'କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିରର ରଥ ଗଠନର ୨୪ଟି ଜଟିଳ ଭାବରେ ଖୋଦିତ ପଥର ଚକ ମଧ୍ୟରୁ ଗୋଟିଏ। ଏହି ଚକଗୁଡ଼ିକ କେବଳ ସାଜସଜ୍ଜା ନୁହେଁ ବରଂ ସୂର୍ଯ୍ୟଘଡ଼ି ଭାବରେ ମଧ୍ୟ କାର୍ଯ୍ୟ କରନ୍ତି।',
    },
    imageUrlId: 'konark-wheel-artifact',
    modelFileUrl: '/models/konark_wheel.glb',
    fallbackImageUrlId: 'konark-wheel-artifact',
  },
];

const allSites: Site[] = [
  {
    id: 'site-1',
    title: {
      en: 'Taj Mahal',
      hi: 'ताज महल',
      kn: 'ತಾಜ್ ಮಹಲ್',
      or: 'ତାଜମହଲ',
    },
    shortDescription: {
      en: 'An ivory-white marble mausoleum on the south bank of the Yamuna river.',
      hi: 'यमुना नदी के दक्षिणी तट पर एक हाथीदांत-सफेद संगमरमर का मकबरा।',
      kn: 'ಯಮುನಾ ನದಿಯ ದಕ್ಷಿಣ ತೀರದಲ್ಲಿ ಇರಿಸಿಕೊಡಲಿರುವ ಬಿಳಿ ಸಂಗ್ರಹ ಶಿಲಾ ಸಮಾಧಿ.',
      or: 'ଯମୁନା ନଦୀର ଦକ୍ଷିଣ କୂଳରେ ଥିବା ଏକ ହାତୀଦାନ୍ତ-ଧଳା ମାର୍ବଲ ସମାଧି।',
    },
    longDescription: {
      en: 'The Taj Mahal is an immense mausoleum of white marble, built in Agra between 1631 and 1648 by order of the Mughal emperor Shah Jahan in memory of his favourite wife. The Taj Mahal is the jewel of Muslim art in India and one of the universally admired masterpieces of the world\'s heritage.',
      hi: 'ताजमहल सफेद संगमरमर का एक विशाल मकबरा है जो 1631 और 1648 के बीच मुगल सम्राट शाहजहाँ के आदेश पर उनकी प्रिय पत्नी की स्मृति में आगरा में बनाया गया था। यह भारत में मुस्लिम कला का अनमोल रत्न है।',
      kn: 'ತಾಜ್ ಮಹಲ್ ಬಿಳಿ ಕಾಮನೀಲಿ ನೀಲಿಪದ ಪದಾರ್ಥದಿಂದ ನಿರ್ಮಿತ ಭವ್ಯ ಸಮಾಧಿ; 1631ರಿಂದ 1648ರ ನಡುವೆ ಮೊಘಲ್ ಸಾಮ್ರಾಟ್ ಶಾಹಜಹಾನ್ ಅವರ ಆದೇಶದಡಿ ಅವರ ಪ್ರಿಯ ಪತ್ನಿಯ ಸ್ಮರಣಾರ್ಥವಾಗಿ ಆಗ್ರಾದಲ್ಲಿ ನಿರ್ಮಿಸಲಾಯಿತು. ತಾಜ್ ಮಹಲ್ ಭಾರತದಲ್ಲಿನ ಮುಸ್ಲಿಂ ಕಲೆಯ ಅಮೂಲ್ಯ ರತ್ನವಾಗಿದೆ.',
      or: 'ତାଜମହଲ ଏକ ବିଶାଳ ଧଳା ମାର୍ବଲର ସମାଧି, ଯାହା ୧୬୩୧ ରୁ ୧୬୪୮ ମଧ୍ୟରେ ଆଗ୍ରାରେ ମୋଗଲ ସମ୍ରାଟ ଶାହଜାହାନଙ୍କ ଆଦେଶରେ ତାଙ୍କ ପ୍ରିୟ ପତ୍ନୀଙ୍କ ସ୍ମୃତିରେ ନିର୍ମିତ ହୋଇଥିଲା। ତାଜମହଲ ଭାରତରେ ମୁସଲିମ କଳାର ଏକ ଅମୂଲ୍ୟ ରତ୍ନ ଏବଂ ବିଶ୍ୱ ଐତିହ୍ୟର ସର୍ବଭାରତୀୟ ପ୍ରଶଂସିତ କୃତି ମଧ୍ୟରୁ ଗୋଟିଏ।',
    },
    thumbnailUrlId: 'taj-mahal-thumb',
    coverImageUrlId: 'taj-mahal-cover',
    lowPolyModelUrl: '/models/taj_low.glb',
    highPolyModelUrl: '/models/taj_mahal_3d_model.glb',
    fallback360UrlId: 'fallback-360-taj',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-1'),
  },
  {
    id: 'site-2',
    title: {
      en: 'Hampi Chariot',
      kn: 'ಹಂಪಿ ರಥ',
      hi: 'हम्पी रथ',
      or: 'ହାମ୍ପି ରଥ',
    },
    shortDescription: {
      en: 'The ruined city of Vijayanagara, the former capital of the Vijayanagara Empire.',
      hi: 'विजयनगर का खंडहर शहर, विजयनगर साम्राज्य की पूर्व राजधानी।',
      kn: 'ವಿಜಯನಗರದ ಹರಡಿರುವ ಹಾಳಾದ ನಗರ, ಈ ಪ್ರದೇಶ ಐತಿಹಾಸಿಕವಾಗಿ ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯದ ರಾಜಧಾನಿಯಾಗಿತ್ತು.',
      or: 'ବିଜୟନଗରର ଧ୍ୱଂସାବଶେଷ ସହର, ବିଜୟନଗର ସାମ୍ରାଜ୍ୟର ପୂର୍ବତନ ରାଜଧାନୀ।',
    },
    longDescription: {
      en: 'Hampi, seat of the famed Vijayanagara empire, contains 14th-century ruins across a large rocky landscape. The stone chariot is one of Hampi\'s best-known attractions.',
      hi: 'हम्पी, प्रसिद्ध विजयनगर साम्राज्य का केंद्र, चौदहवीं सदी के खंडहरों से भरा एक विशाल चट्टानी क्षेत्र है। पत्थर का रथ यहां की प्रमुख आकर्षणों में से एक है।',
      kn: 'ಹಂಪಿ ಪ್ರಸಿದ್ಧ ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯದ ಕೇಂದ್ರವಾಗಿತ್ತು; 14ನೇ ಶತಮಾನಕ್ಕೆ ಸೇರಿದ ಅವಶೇಷಗಳು ದೊಡ್ಡ ಕಲ್ಲು ಪ್ರದೇಶದಲ್ಲಿ ವ್ಯಾಪಿಸಿರುವಿವೆ. ಕಲ್ಲಿನ ರಥವು ಹಂಪಿಯ ಪ್ರಮುಖ ಪ್ರವಾಸಿ ಆಕರ್ಷಣೆಗಳ biridir.',
      or: 'ପ୍ରସିଦ୍ଧ ବିଜୟନଗର ସାମ୍ରାଜ୍ୟର ଆସନ ହାମ୍ପି, ଏକ ବଡ଼ ପଥରଭରା ଭୂମିରେ ୧୪ଶ ଶତାବ୍ଦୀର ଧ୍ୱଂସାବଶେଷ ଧାରଣ କରେ। ପଥର ରଥ ହାମ୍ପିର ସବୁଠାରୁ ଜଣାଶୁଣା ଆକର୍ଷଣ ମଧ୍ୟରୁ ଗୋଟିଏ।',
    },
    thumbnailUrlId: 'hampi-thumb',
    coverImageUrlId: 'hampi-cover',
    lowPolyModelUrl: '/models/hampi_low.glb',
    highPolyModelUrl: '/models/stone_chariot_in_hampi.glb',
    fallback360UrlId: 'fallback-360-hampi',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-2'),
  },
  {
    id: 'site-3',
    title: {
      en: 'Qutub Minar',
      hi: 'कुतुब मीनार',
      kn: 'ಕುತುಬ್ ಮಿನಾರ್',
      or: 'କୁତୁବ ମିନାର',
    },
    shortDescription: {
      en: 'A minaret and "victory tower" that forms part of the Qutb complex.',
      hi: 'कुतुब परिसर का एक मीनार और "विजय मंडप"।',
      kn: 'ಕುತುಬ್ ಸಂಕೀರ್ಣದಲ್ಲಿ ಭಾಗವಿರುವ ಮಿನಾರೆಟ್ ಮತ್ತು ವೀಕ್ಷಣ ಗೋಪುರ.',
      or: 'ଏକ ମିନାର ଏବଂ "ବିଜୟ ସ୍ତମ୍ଭ" ଯାହା କୁତବ କମ୍ପ୍ଲେକ୍ସର ଏକ ଅଂଶ।',
    },
    longDescription: {
      en: 'The Qutub Minar is a towering 73-meter high tower built by Qutub-ud-Din Aibak in 1193. It was built to celebrate the establishment of Muslim rule in Delhi after earlier events. With five storeys and balconies, it is a historic landmark.',
      hi: 'कुतुब मीनार 1193 में कुतुब-उद-दीन ऐबक द्वारा निर्मित 73 मीटर ऊंचा टॉवर है। यह दिल्ली के ऐतिहासिक बनावट का एक प्रमुख स्मारक है।',
      kn: 'ಕುತುಬ್ ಮಿನಾರ್ 1193ರಲ್ಲಿ ಕುತ್ತಬ್-ಉದ್-ದೀನ್ ಐಬಕ್ ನಿರ್ಮಿಸಿದ 73 ಮೀಟರ್ ಎತ್ತರದ ಗೋಪುರವಾಗಿದೆ. ಐದು ಮಹಡಿಗಳು ಮತ್ತು ಹೊರನೋಟದ ಬಾಲ್ಕನಿಗಳೊಂದಿಗೆ ಇದು ಐತಿಹಾಸಿಕ ಲಕ್ಷಣವಾಗಿದೆ.',
      or: 'କୁତୁବ ମିନାର ୧୧୯୩ ମସିହାରେ କୁତୁବ-ଉଦ-ଦିନ ଆଇବକଙ୍କ ଦ୍ୱାରା ନିର୍ମିତ ଏକ ୭୩-ମିଟର ଉଚ୍ଚ ଟାୱାର। ପୂର୍ବ ଘଟଣା ପରେ ଦିଲ୍ଲୀରେ ମୁସଲିମ ଶାସନ ପ୍ରତିଷ୍ଠା ଉପଲକ୍ଷେ ଏହା ନିର୍ମିତ ହୋଇଥିଲା। ପାଞ୍ଚ ମହଲା ଏବଂ ବାଲକୋନି ସହିତ ଏହା ଏକ ଐତିହାସିକ ସ୍ମାରକୀ।',
    },
    thumbnailUrlId: 'qutub-minar-thumb',
    coverImageUrlId: 'qutub-minar-cover',
    lowPolyModelUrl: '/models/qutub_low.glb',
    highPolyModelUrl: '/models/qutub_minar.glb',
    fallback360UrlId: 'fallback-360-qutub',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-3'),
  },
  {
    id: 'site-4',
    title: {
      en: 'Konark Sun Temple',
      hi: 'कोणार्क सूर्य मंदिर',
      kn: 'ಕೋನಾರ್ಕ್ ಸೂರ್ಯ ದೇವಾಲಯ',
      or: 'କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର',
    },
    shortDescription: {
      en: 'A 13th-century CE sun temple at Konark in Odisha, India.',
      hi: 'ओडिशा के कोणार्क में 13वीं शताब्दी का सूर्य मंदिर।',
      kn: 'ಒಡಿಷಾದ ಕೊಣಾರ್ಕ್‌ನಲ್ಲಿ ಇರುವ 13ನೇ ಶತಮಾನದ ಸೂರ್ಯ ದೇವಾಲಯ.',
      or: 'ଭାରତର ଓଡ଼ିଶାର କୋଣାର୍କରେ ଥିବା ୧୩ଶ ଶତାବ୍ଦୀର ସୂର୍ଯ୍ୟ ମନ୍ଦିର।',
    },
    longDescription: {
      en: 'The Konark Sun Temple is a 13th-century temple dedicated to the Hindu sun god Surya. Shaped like a giant chariot, the temple is known for its exquisite stone carvings that cover the entire structure.',
      hi: 'कोणार्क सूर्य मंदिर 13वीं शताब्दी का मंदिर है जो सूर्य देव को समर्पित है। यह रथ के आकार का है और इसकी पत्थर की नक्काशी बहुत प्रसिद्ध है।',
      kn: 'ಕೊಣಾರ್ಕ್ ಸೂರ್ಯ ದೇವಾಲಯವು 13ನೇ ಶತಮಾನದ ಮೂರ್ತಿಯಾಗಿದೆ; ಇದು ರಥದ ಆಕಾರದಂತೆ ರೂಪಗೊಂಡಿದ್ದು ಸಂಪೂರ್ಣ ರಚನೆಯನ್ನು ಆವರಿಸಿರುವ ಸುಂದರ ಕಲ್ಲಿನ ಕೆತ್ತುಕೆಗಳಿಗಾಗಿ ಪ್ರಸಿದ್ಧವಾಗಿದೆ.',
      or: 'କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର ହିନ୍ଦୁ ସୂର୍ଯ୍ୟ ଦେବତା ସୂର୍ଯ୍ୟଙ୍କୁ ସମର୍ପିତ ଏକ ୧୩ଶ ଶତାବ୍ଦୀର ମନ୍ଦିର। ଏକ ବିଶାଳ ରଥ ଆକାରରେ ନିର୍ମିତ ଏହି ମନ୍ଦିରଟି ସମ୍ପୂର୍ଣ୍ଣ ସଂରଚନାକୁ ଆଚ୍ଛାଦନ କରୁଥିବା ଏହାର ଚମତ୍କାର ପଥର ଖୋଦେଇ ପାଇଁ ଜଣାଶୁଣା।',
    },
    thumbnailUrlId: 'konark-sun-temple-thumb',
    coverImageUrlId: 'konark-sun-temple-cover',
    lowPolyModelUrl: '/models/konark_low.glb',
    highPolyModelUrl: '/models/sun_temple.glb',
    fallback360UrlId: 'fallback-360-konark',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-4'),
  },
  {
    id: 'site-6',
    title: {
      en: 'Rani-ki-Vav',
      hi: 'रानी की वाव',
      kn: 'ರಾಣಿ-ಕಿ-ವಾವ್',
      or: 'ରାଣୀ-କି-ଭାଭ',
    },
    shortDescription: {
      en: 'An intricately constructed stepwell situated in the town of Patan in Gujarat.',
      hi: 'गुजरात के पाटन में स्थित एक जटिल रूप से निर्मित सीढ़ीनुमा बावड़ी।',
      kn: 'ಗುಜರಾತಿನ ಪಾಟಣ ನಗರದೊಂದರಲ್ಲಿ ಸ್ಥಿತವಾಗಿರುವ ಸೂಕ್ಷ್ಮವಾಗಿ ನಿರ್ಮಿಸಲಾದ ಮೆಟ್ಟಿಲು ಬಾವಿ.',
      or: 'ଗୁଜରାଟର ପାଟଣ ସହରରେ ଅବସ୍ଥିତ ଏକ ଜଟିଳ ଭାବରେ ନିର୍ମିତ ପାହାଚକୂପ।',
    },
    longDescription: {
      en: 'Rani-ki-Vav is an exceptional example of a stepwell (subterranean water architecture) built in the 11th century as a memorial to a king. It is designed like an inverted temple highlighting the sanctity of water.',
      hi: 'रानी की वाव एक असाधारण सीढ़ीनुमा बावड़ी का उदाहरण है, जिसे 11वीं शताब्दी में एक राजा की स्मृति में बनाया गया था। यह पानी की पवित्रता को उजागर करता है।',
      kn: 'ರಾಣಿ-ಕಿ-ವಾವ್ 11 ನೇ ಶತಮಾನದಲ್ಲಿ ನಿರ್ಮಿಸಲಾದ ಮೆಟ್ಟಿಲುಬಾವಿಯ ಅದ್ಭುತ ಉದಾಹರಣೆ; ಇದು ನೀರಿನ ಪವಿತ್ರತೆಯನ್ನು ಪ್ರದರ್ಶಿಸುವಂತೆ ಉಪದೇವಾಲಯದ ರೂಪದಲ್ಲಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.',
      or: 'ରାଣୀ-କି-ଭାଭ ଏକାଦଶ ଶତାବ୍ଦୀରେ ଜଣେ ରାଜାଙ୍କ ସ୍ମୃତିରେ ନିର୍ମିତ ଏକ ପାହାଚକୂପର (ଭୂତଳ ଜଳ ସ୍ଥାପତ୍ୟ) ଏକ ଅସାଧାରଣ ଉଦାହରଣ। ଏହାକୁ ଏକ ଓଲଟା ମନ୍ଦିର ପରି ପରିକଳ୍ପନା କରାଯାଇଛି ଯାହା ଜଳର ପବିତ୍ରତାକୁ ଦର୍ଶାଏ।',
    },
    thumbnailUrlId: 'rani-ki-vav-thumb',
    coverImageUrlId: 'rani-ki-vav-cover',
    lowPolyModelUrl: '/models/rani_ki_vav_low.glb',
    highPolyModelUrl: '/models/rani-ki-vav.glb',
    fallback360UrlId: 'fallback-360-rani-ki-vav',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-6'),
  },
  {
    id: 'site-7',
    title: {
      en: 'Charminar',
      hi: 'चारमीनार',
      kn: 'ಚಾರ್ಮಿನಾರ್',
      or: 'ଚାରମିନାର',
    },
    shortDescription: {
      en: 'A monument and mosque located in Hyderabad, Telangana, India.',
      hi: 'हैदराबाद, तेलंगाना में स्थित एक स्मारक और मस्जिद।',
      kn: 'ತೆಲಂಗಾಣದ ಹೈದರಾಬಾದ್‌ಸ್ಥCharಪಾಪದಲ್ಲಿರುವ ಸಂಕೇತ ಮತ್ತು ಮಸೀದಿ.',
      or: 'ଭାରତର ତେଲେଙ୍ଗାନାର ହାଇଦ୍ରାବାଦରେ ଅବସ୍ଥିତ ଏକ ସ୍ମାରକୀ ଏବଂ ମସଜିଦ।',
    },
    longDescription: {
      en: 'The Charminar, constructed in 1591, is a monument and mosque located in Hyderabad. The landmark has become an icon of the city and a well-known symbol of India’s heritage.',
      hi: 'चारमीनार, 1591 में निर्मित, हैदराबाद में स्थित एक स्मारक और मस्जिद है। यह शहर का प्रतीक बन चुका है।',
      kn: 'ಚಾರ್ಮಿನಾರ್ 1591 ರಲ್ಲಿ ನಿರ್ಮಿಸಲ್ಪಟ್ಟಿರುವ ಹೈದರಾಬಾದ್‌ನ ಪ್ರಮುಖ ಸ್ಮಾರಕ ಮತ್ತು ಮಸೀದಿಯಾಗಿದೆ; ಇದು ನಗರದ ಐಕಾನ್ ಆಗಿದೆ.',
      or: '୧୫୯୧ ମସିହାରେ ନିର୍ମିତ ଚାରମିନାର ହାଇଦ୍ରାବାଦରେ ଅବସ୍ଥିତ ଏକ ସ୍ମାରକୀ ଏବଂ ମସଜିଦ। ଏହି ସ୍ଥାନଟି ସହରର ଏକ ପ୍ରତୀକ ଏବଂ ଭାରତର ଐତିହ୍ୟର ଏକ ଜଣାଶୁଣା ପ୍ରତୀକ ପାଲଟିଛି।',
    },
    thumbnailUrlId: 'charminar-thumb',
    coverImageUrlId: 'charminar-cover',
    lowPolyModelUrl: '/models/charminar_low.glb',
    highPolyModelUrl: '/models/charminar_hyderabad.glb',
    fallback360UrlId: 'fallback-360-charminar',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-7'),
  },
  {
    id: 'site-8',
    title: {
      en: 'Jagannath Puri Temple',
      hi: 'जगन्नाथ पुरी मंदिर',
      kn: 'ಜಗನ್ನಾಥ ಪುರಿ ದೇವಾಲಯ',
      or: 'ଜଗନ୍ନାଥ ପୁରୀ ମନ୍ଦିର',
    },
    shortDescription: {
      en: 'An important Hindu temple dedicated to Jagannath, a form of Vishnu.',
      hi: 'विष्णु के रूप जगन्नाथ को समर्पित एक महत्वपूर्ण हिंदू मंदिर।',
      kn: 'ವಿಷ್ಣುವಿನ ಆ ರೂಪವಾದ ಜಗನ್ನಾಥಕ್ಕಾಗಿ ಸಮರ್ಪಿತ ಪ್ರಮುಖ ಹಿಂದೂ ದೇವಾಲಯ.',
      or: 'ବିଷ୍ଣୁଙ୍କର ଏକ ରୂପ ଜଗନ୍ନାଥଙ୍କୁ ସମର୍ପିତ ଏକ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ହିନ୍ଦୁ ମନ୍ଦିର।',
    },
    longDescription: {
      en: 'The Shri Jagannath Temple of Puri is an important Hindu temple dedicated to Jagannath. The present temple was rebuilt from the 10th century onwards, begun by King Anantavarman Chodaganga Deva of the Eastern Ganga dynasty.',
      hi: 'पुरी का श्री जगन्नाथ मंदिर जगन्नाथ को समर्पित एक महत्वपूर्ण हिंदू मंदिर है। वर्तमान मंदिर 10वीं शताब्दी के बाद के समय में पुनर्निर्मित किया गया था, जिसकी शुरुआत पूर्वी गंगा वंश के राजा अनंतवर्मन चोड़गंग देव ने की थी।',
      kn: 'ಪುರಿಯ ಶ್ರೀ ಜಗನ್ನಾಥ ದೇವಸ್ಥಾನವು ಜಗನ್ನಾಥನಿಗೆ ಸಮರ್ಪಿತ ಪ್ರಮುಖ ಹಿಂದೂ ದೇವಾಲಯವಾಗಿದ್ದು, 10ನೇ ಶತಮಾನದಿಂದ ಆರಂಭವಾಗಿ ಪುನರ್ನಿರ್ಮಿಸಲ್ಪಟ್ಟಿದೆ. ಇದನ್ನು ಪೂರ್ವ ಗಂಗ ವಂಶದ ರಾಜ ಅನಂತವರ್ಮನ್ ಚೋಡಗಂಗ ದೇವರು ಪ್ರಾರಂಭಿಸಿದ್ದರು.',
      or: 'ପୁରୀର ଶ୍ରୀ ଜଗନ୍ନାଥ ମନ୍ଦିର ଜଗନ୍ନାଥଙ୍କୁ ସମର୍ପିତ ଏକ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ହିନ୍ଦୁ ମନ୍ଦିର। ବର୍ତ୍ତମାନର ମନ୍ଦିରଟି ଦଶମ ଶତାବ୍ଦୀରୁ ପୁନର୍ବାର ନିର୍ମିତ ହୋଇଥିଲା, ଯାହା ପୂର୍ବ ଗଙ୍ଗା ରାଜବଂଶର ରାଜା ଅନନ୍ତବର୍ମନ ଚୋଡ଼ଗଙ୍ଗ ଦେବଙ୍କ ଦ୍ୱାରା ଆରମ୍ଭ କରାଯାଇଥିଲା।',
    },
    thumbnailUrlId: 'jagannath-puri-thumb',
    coverImageUrlId: 'jagannath-puri-cover',
    lowPolyModelUrl: '/models/jagannath_puri_low.glb',
    highPolyModelUrl: '/models/jagannath_puri_temple_model.glb',
    fallback360UrlId: 'fallback-360-jagannath-puri',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-8'),
  },
  {
    id: 'site-9',
    title: {
      en: 'Ellora Caves',
      hi: 'एलोरा गुफाएं',
      kn: 'ಎಲ್ಲೋರಾ ಗುಹೆಗಳು',
      or: 'ଏଲୋରା ଗୁମ୍ଫା',
    },
    shortDescription: {
      en: 'A UNESCO World Heritage Site located in the Aurangabad district of Maharashtra.',
      hi: 'महाराष्ट्र के औरंगाबाद जिले में स्थित एक यूनेस्को विश्व धरोहर स्थल।',
      kn: 'ಮಹಾರಾಷ್ಟ್ರದ ಔರಂಗಾಬಾದ್ ಜಿಲ್ಲೆಯಲ್ಲಿರುವ ಯುನೆಸ್ಕೋ ವಿಶ್ವ ಪರಂಪರೆ ತಾಣ.',
      or: 'ମହାରାଷ୍ଟ୍ରର ଔରଙ୍ଗାବାଦ ଜିଲ୍ଲାରେ ଅବସ୍ଥିତ ଏକ ୟୁନେସ୍କୋ ବିଶ୍ୱ ଐତିହ୍ୟ ସ୍ଥଳୀ।',
    },
    longDescription: {
      en: 'Ellora is one of the largest rock-cut monastery-temple cave complexes in the world, featuring Hindu, Buddhist and Jain monuments and artwork, dating from the 600–1000 CE period. Cave 16 (Kailasha) features the largest single monolithic rock excavation in the world.',
      hi: 'एलोरा दुनिया के सबसे बड़े शिला-निर्मित मठ-मंदिर गुफ़ा परिसरों में से एक है, जिसमें हिंदू, बौद्ध और जैन स्मारक और कलाकृतियां हैं। गुफा 16 (कैलाश) दुनिया की सबसे बड़ी एकल शिलाखनन है।',
      kn: 'ಎಲ್ಲೋರಾ ವಿಶ್ವದ ಅತಿದೊಡ್ಡ ಶಿಲಾ-ತೋರಿತ ಮಠ-ಮಂದಿರ ಗುಹಾ ಸಂಕೀರ್ಣಗಳಲ್ಲಿ ಒಂದಾಗಿದ್ದು, 600–1000 ಕ್ರಿ.ಶ. ಅವಧಿಯ ಹಿಂದೂ, ಬೌದ್ಧ ಮತ್ತು ಜೈನ ಸ್ಮಾರಕಗಳು ಹಾಗೂ ಕಲಾಕೃತಿಗಳನ್ನು ಒಳಗೊಂಡಿದೆ. ಗುಹೆ 16 (ಕೈಲಾಶ) ವಿಶ್ವದ ಅತಿದೊಡ್ಡ ಏಕಶಿಲಾ ಉಕ್ಕುವ ಕಾರ್ಯವಾಗಿದೆ.',
      or: 'ଏଲୋରା ବିଶ୍ୱର ସବୁଠାରୁ ବଡ଼ ପଥର-କଟା ମଠ-ମନ୍ଦିର ଗୁମ୍ଫା କମ୍ପ୍ଲେକ୍ସ ମଧ୍ୟରୁ ଗୋଟିଏ, ଯେଉଁଥିରେ ହିନ୍ଦୁ, ବୌଦ୍ଧ ଏବଂ ଜୈନ ସ୍ମାରକୀ ଏବଂ କଳାକୃତି ରହିଛି, ଯାହା ୬୦୦–୧୦୦୦ ଖ୍ରୀଷ୍ଟାବ୍ଦରୁ ଆରମ୍ଭ ହୋଇଥିଲା। ଗୁମ୍ଫା ୧୬ (କୈଳାଶ)ରେ ବିଶ୍ୱର ସବୁଠାରୁ ବଡ଼ ଏକକ ଏକଶିଳା ପଥର ଖନନ ଦେଖିବାକୁ ମିଳେ।',
    },
    thumbnailUrlId: 'ellora-caves-thumb',
    coverImageUrlId: 'ellora-caves-cover',
    lowPolyModelUrl: '/models/ellora_caves_low.glb',
    highPolyModelUrl: '/models/ellora_caves__india.glb',
    fallback360UrlId: 'fallback-360-ellora-caves',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-9'),
  },
  {
    id: 'site-10',
    title: {
      en: 'Sanchi Stupa',
      hi: 'सांची स्तूप',
      kn: 'ಸಾಂಚಿ ಸ್ತೂಪ',
      or: 'ସାଞ୍ଚି ସ୍ତୂପ',
    },
    shortDescription: {
      en: 'A Buddhist complex, famous for its Great Stupa, on a hilltop at Sanchi Town in Madhya Pradesh.',
      hi: 'मध्य प्रदेश के सांची टाउन में एक पहाड़ी पर स्थित एक बौद्ध परिसर, जो अपने महान स्तूप के लिए प्रसिद्ध है।',
      kn: 'ಮಧ್ಯಪ್ರದೇಶದ ಸಾಂಚಿ ಪಟ್ಟಣದಲ್ಲಿ ಗುಡ್ಡಮೇಲಿನ ಮಹಾಸ್ತೂಪಕ್ಕಾಗಿ ಪ್ರಸಿದ್ಧವಾದ ಬೌದ್ಧ ಸಂಕೀರ್ಣ.',
      or: 'ମଧ୍ୟପ୍ରଦେଶର ସାଞ୍ଚି ସହରର ଏକ ପାହାଡ଼ ଉପରେ ଥିବା ଏକ ବୌଦ୍ଧ କମ୍ପ୍ଲେକ୍ସ, ଯାହା ଏହାର ମହାନ ସ୍ତୂପ ପାଇଁ ପ୍ରସିଦ୍ଧ।',
    },
    longDescription: {
      en: 'The Great Stupa at Sanchi is one of the oldest stone structures in India and was originally commissioned by Emperor Ashoka in the 3rd century BCE. Its nucleus was a simple hemispherical brick structure built over the relics of the Buddha.',
      hi: 'सांची का महान स्तूप भारत की प्राचीनतम पत्थर की संरचनाओं में से एक है, जिसका मूल आदेश सम्राट अशोक ने तीसरी सदी ईसा पूर्व में दिया था। इसका केंद्र बुद्ध के अवशेषों पर निर्मित एक गोलाकार ईंट संरचना था।',
      kn: 'ಸಾಂಚಿಯ ಮಹಾಸ್ತೂಪವು ಭಾರತದ ಅತ್ಯಂತ ಹಳೆಯ ಕಲ್ಲಿನ ರಚನೆಗಳಲ್ಲಿ ಒಂದಾಗಿದ್ದು, ಕ್ರಿ.ಪೂ. 3 ನೇ ಶತಮಾನದ ವೇಳೆ ಅಶೋಕನ ಆದೇಶದೊಂದಿಗೆ ಆರಂಭಿಸಲಾಯಿತು. ಇದರ ಕೇಂದ್ರ ಭಾಗದಲ್ಲಿ ಬುದ್ಧನ ಅವಶೇಷಗಳ ಮೇಲೆ ನಿರ್ಮಿಸಲಾದ ಸರಳ ಅರ್ಧಗೋಳಾಕಾರದ ಇಟ್ಟಿಗೆಯ ರಚನೆ ಇದ್ದಿತು.',
      or: 'ସାଞ୍ଚିର ମହାନ ସ୍ତୂପ ଭାରତର ସବୁଠାରୁ ପୁରାତନ ପଥର ସଂରଚନା ମଧ୍ୟରୁ ଗୋଟିଏ ଏବଂ ଏହା ମୂଳତଃ ଖ୍ରୀଷ୍ଟପୂର୍ବ ୩ୟ ଶତାବ୍ଦୀରେ ସମ୍ରାଟ ଅଶୋକଙ୍କ ଦ୍ୱାରା ନିର୍ମିତ ହୋଇଥିଲା। ଏହାର କେନ୍ଦ୍ରଟି ବୁଦ୍ଧଙ୍କ ଅବଶେଷ ଉପରେ ନିର୍ମିତ ଏକ ସରଳ ଅର୍ଦ୍ଧଗୋଲାକାର ଇଟା ସଂରଚନା ଥିଲା।',
    },
    thumbnailUrlId: 'sanchi-stupa-thumb',
    coverImageUrlId: 'sanchi-stupa-cover',
    lowPolyModelUrl: '/models/sanchi_stupa_low.glb',
    highPolyModelUrl: '/models/great_stupa_in_sanchi.glb',
    fallback360UrlId: 'fallback-360-sanchi-stupa',
    artifacts: allArtifacts.filter((a) => a.siteId === 'site-10'),
  },
];

export const getSites = (): Site[] => allSites;

export const getSiteById = (id: string): Site | undefined => allSites.find((site) => site.id === id);

export const getArtifacts = (): Artifact[] => allArtifacts;

export const getArtifactById = (id: string): Artifact | undefined => allArtifacts.find((artifact) => artifact.id === id);
